default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgresqldb_jvz0_user
  password: UaUkEkoLqrrGTfG5StZUOLZuN667zK32
  host: dpg-ch2hhvl269v61fdd7470-a.singapore-postgres.render.com
  port: 5432

development:
  <<: *default
  database: SecureAuthApp_development

test:
  <<: *default
  database: SecureAuthApp_test

production:
  <<: *default
  database: SecureAuthApp_production
